[package]
name = "scratch"
description = "Testbed for hacking on mtg_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
mtg_engine = { path = "../mtg_engine" }

env_logger = "0.9.0"
log = "0.4.14"
